extrn hIcon: dword
extrn hBitmapText: dword
extrn hBitmapBgnd: dword
extrn hBitmapBgnd1: dword
extrn hBitmapBgnd2: dword
extrn hBitmapBgnd3: dword
extrn hBitmapBgnd4: dword
extrn hBitmapBgnd5: dword
extrn hBitmapAdd: dword
extrn hBitmapAdd1: dword
extrn hBitmapAdd2: dword
extrn hBitmapAdd3: dword
extrn hBitmapAdd4: dword
extrn hBitmapAdd5: dword
extrn hBitmapDelete: dword
extrn hBitmapDelete1: dword
extrn hBitmapDelete2: dword
extrn hBitmapDelete3: dword
extrn hBitmapDelete4: dword
extrn hBitmapDelete5: dword
extrn hBitmapDrag: dword
extrn hBitmapDrag1: dword
extrn hBitmapDrag2: dword
extrn hBitmapDrag3: dword
extrn hBitmapDrag4: dword
extrn hBitmapDrag5: dword

_ImagesPreload proto
